### ISSUE TITLE
jupyter config file 및 theme 적용 요청

### ISSUE THREAD

**Issue by dbnoid** [teddylee777/docker-kaggle-ko#1]
안녕하세요?
수고해 주신 덕분에 docker 이미지 잘 사용하고 있습니다. (이미지를 다운받아 사용중)
지식이 부족하여 부탁과 문의를 남깁니다.

1. 추가 설치된 항목과 Python 패키지 항목에 jupyter_notebook_config.py 가 있는데 아무리 찾아도 해당 파일이 도커내에 없네요.
2. 노안이 오는 40대 중후반인지라 다크테마로 Jupyter Notebook을 사용하고 싶은데  혹시 적용 검토 가능하실지요?

docker를 사용한지 얼마되지 않아 지식이 부족하지만 저도 앞으로 귀하처럼 이런 이미지를 만들어 보고 싶네요
감사합니다.

**Comment by teddylee777** [comment]
@dbnoid 님 안녕하세요?

잘 사용하고 계시다니 뿌듯합니다 :)

issue 남겨주신 부분에 대한 답변 드리겠습니다.

1. 추가 설치된 항목과 Python 패키지 항목에 jupyter_notebook_config.py 가 있는데 아무리 찾아도 해당 파일이 도커내에 없네요.

답변:
docker에서 image를 pull 하시면 jupyter_notebook_config.py 파일이 들어있지 않습니다. 원래는 copy해서 image 내부에 위치할 수 있도록 패키징을 했었는데요. config 설정은 docker image를 pull 하여 사용하시는 분들마다 다르게 설정해야하는 부분이라 image에 포함하여 배포하는 것은 배제 하였습니다.

하지만, gpu.Dockerfile에 살펴보시면 하단에 주석처리해 놓았습니다.
주석을 푸신 후 로컬에서 빌드하시면 jupyter_notebook_config.py가 자동으로 복사되도록 수정하실 수 있구요.

아니면 github에서 jupyter_notebook_config.py 파일이 업로드 되어 있으니, 직접 copy하시는 방법도 있습니다.

```
# Jupyter Notebook config 파일 생성
# RUN jupyter notebook --generate-config

# config 파일 복사 (jupyter_notebook_config.py 파일 참고)
# COPY jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py

# 설치 완료 후 테스트용 ipynb
# COPY test.ipynb /home/jupyter/test.ipynb

# 기본
EXPOSE 8888
# jupyter notebook 의 password를 지정하지 않으면 보안상 취약하므로 지정하는 것을 권장
# CMD jupyter notebook --allow-root
```

2. 노안이 오는 40대 중후반인지라 다크테마로 Jupyter Notebook을 사용하고 싶은데 혹시 적용 검토 가능하실지요?

답변:
테마 역시 1번에 대한 답변과 결이 같습니다.
테마 적용도 개개인의 선호도에 따라 설정을 달리 적용해야하는 부분이라서 image를 pull 한 뒤, 컨테이너 생성 후 jupyter 관련 설정 파일을 수정하시는 것이 더 적합하다고 생각합니다.

jupyter 의 테마 변경은 블로그에 검색해 보시면 쉽게 찾으실 수 있습니다.

docker 컨테이너가 running되고 있는 상태에서 수정하신 뒤 변경사항을 docker save로 변경사항을 저장해 놓으시면 매번 실행시 설정해야하는 수로고움을 더실 수 있을 것 같습니다.

감사합니다.

**Comment by teddylee777** [comment]
아 깜빡하고 말씀 안드린 부분이 있네요.

다음 번 배포때에는 jupytertheme 패키지를 설치하여, 사용자 개개인이 테마 변경을 쉽게 하실 수 있도록 기능 추가 하도록 하겠습니다.

감사합니다.

**Comment by dbnoid** [comment]
@teddylee777 님 답변 감사드립니다.

다음 배포에 테마를 포함해 주신다니 감사드립니다.
어제 이슈를 등록한뒤  jupyter config  파일과 관련하여 깃허브의 소스에서 말씀하신부분을 일부 찾았습니다.
자체적으로 빌드를 하면 올려주시는 배포판의 판올림이 있을경우 자체 빌드를 다시해야 할 거 같다는 생각에 이슈등록을 했었습니다.
직접 copy하는 방법을 고려하여 테스트 해보도록 하겠습니다.

다시한번 수고에 감사드립니다.

**Comment by teddylee777** [comment]
@dbnoid 님
방금 jupyter-theme을 반영한 새로운 이미지를 배포하였습니다.
가장 최신 도커 이미지를 pull 해서 테스트 해주시면 되겠습니다^^

jupyter lab으로 실행해 주시면 되고요, 
서버주소(혹은 localhost):8888/lab
으로 접속하시면 상단에 테마 - 다크테마 적용 가능합니다!

![image](https://user-images.githubusercontent.com/10074379/190689016-89689785-2429-4469-bfb7-031306510722.png)

좋은 의견 주셔서 감사합니다.

**Comment by dbnoid** [comment]
@teddylee777 님
새로 반영하신 이미지를 적용해 봤습니다.
말씀하신 lab은 아니고 jupyter notebook에 적용을 확인했습니다.
![image](https://user-images.githubusercontent.com/52301635/190836185-fa2793cf-6224-4e75-9bbf-61fa787c6869.png)
잘 적용됨을 확인했습니다.

한글 폰트를 적요하고 싶었는데 오류가 나는것을 찾아보느라 시간이 좀 오래걸렸네요
해당 내용은 아래 [블로그](https://velog.io/@yoonkeee/Jupyter-Notebook-%ED%8F%B0%ED%8A%B8-%EB%B3%80%EA%B2%BD-%EC%A0%9C%EB%8C%80%EB%A1%9C-%ED%95%98%EA%B8%B0-WITHOUT-CSS)를 보고 적용을 해봤습니다.

아직 갈길이 먼  데이터 분석의 길이네요...
좋은 주말 보내시길 바랍니다.
노고에 감사드립니다.
